#---------------------------------------------------------------------
# GitHub Action Workflow Basics
#
# Version      Date        Info
# 1.0          2019        Initial Version
#
# Made by Denis Astahov ADV-IT Copyleft (c) 2019
#---------------------------------------------------------------------
name: My-GitHubActions-Basics
env:
  make lint    : npx eslint bin
  DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"

on: 
  push:
    branches: 
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: start Eslint
      run : make lint
