#---------------------------------------------------------------------
# GitHub Action Workflow Basics
#
# Version      Date        Info
# 1.0          2019        Initial Version
#
# Made by Denis Astahov ADV-IT Copyleft (c) 2019
#---------------------------------------------------------------------
name: My-GitHubActions-Basics
env:
<<<<<<< HEAD
  APPLICATION_NAME    : "MyFlask"
=======
  make lint    : npx eslint
>>>>>>> 29ad968a579b01eb1c36c0fb9bd2ac7a7f23710e
  DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"

on: 
  push:
    branches: 
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Npm install
      run : node --version
      
    
  
  
  
